# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ECrfs_BKZLU9nuIi8UHfypibE2-B_0R
"""

import pandas as pd
import requests
import time
import os

TMDB_API_KEY = "YOUR_API_KEY"

movies = pd.read_csv("movies.csv")

# ==============================
# LOAD EXISTING (RESUME SUPPORT)
# ==============================
if os.path.exists("posters.csv"):
    posters_df = pd.read_csv("posters.csv")
    done_ids = set(posters_df["movieId"].tolist())
    poster_data = posters_df.to_dict("records")
    print(f"Resuming... already have {len(done_ids)} posters")
else:
    poster_data = []
    done_ids = set()
    print("Starting fresh...")

# ==============================
# FUNCTION
# ==============================
def get_poster(title):
    try:
        clean = title.split('(')[0].strip()

        url = "https://api.themoviedb.org/3/search/movie"
        params = {
            "api_key": TMDB_API_KEY,
            "query": clean
        }

        res = requests.get(url, params=params, timeout=5)

        if res.status_code != 200:
            return None

        data = res.json()
        results = data.get("results")

        if results and len(results) > 0:
            poster_path = results[0].get("poster_path")
            if poster_path:
                return f"https://image.tmdb.org/t/p/w300{poster_path}"

        return None

    except Exception as e:
        return None


# ==============================
# LOOP
# ==============================
for i, row in movies.iterrows():

    movie_id = row["movieId"]

    # 🔁 Skip already done
    if movie_id in done_ids:
        continue

    poster = get_poster(row["title"])

    poster_data.append({
        "movieId": movie_id,
        "poster": poster
    })

    done_ids.add(movie_id)

    print(f"{i} done")

    # 💾 AUTOSAVE every 100 movies
    if i % 100 == 0:
        pd.DataFrame(poster_data).to_csv("posters.csv", index=False)
        print("💾 Saved progress...")

    # ⏱️ Avoid rate limit
    time.sleep(0.2)


# ==============================
# FINAL SAVE
# ==============================
pd.DataFrame(poster_data).to_csv("posters.csv", index=False)

print("✅ DONE! posters.csv ready")

import os
print(os.listdir())

from google.colab import files
files.download("posters.csv")